database:
  image: mysql:5.7
  container_name: airlims_db
  environment:
    - MYSQL_DATABASE=lims
    - MYSQL_USER=felix
    - MYSQL_PASSWORD=abc123
    - MYSQL_ROOT_PASSWORD=abc123
    - TZ=America/Los_Angeles
  ports:
    - "3306:3306"
redis:
  image: "redis"
  command: redis-server --appendonly yes
  ports:
    - "6379:6379"